include:
  remote: "https://github.com/git-developer/docker-support/raw/v3.3.1/gitlab-ci/docker-support.yml"

stages:
- post_checkout

trigger_on_update:
  extends: .docker_support:.trigger_on_update
  stage: post_checkout
  dependencies: []

run_matrix_build:
  extends: .docker_support:.build_job
  stage: post_checkout
  trigger:
    include:
    - project: 'ckware/solarview-base'
      file:    '.build-yml'
    forward:
      pipeline_variables: true
  parallel:
    matrix:
      - RUNTIME_BASE_IMAGE: "debian:bullseye-slim"
        IMAGE_PLATFORMS:    "linux/amd64,linux/i386,linux/arm64,linux/arm/v7,linux/arm/v6"
      - RUNTIME_BASE_IMAGE: "debian:buster-slim"
        IMAGE_PLATFORMS:    "linux/amd64,linux/i386,linux/arm64,linux/arm/v7"
        QUALIFIER:          "buster"
      - RUNTIME_BASE_IMAGE: "debian:buster-20220801-slim"
        IMAGE_PLATFORMS:    "linux/arm/v6"
        QUALIFIER:          "buster-20220801"
