include:
  remote: "https://github.com/git-developer/docker-support/raw/v3.0.0/gitlab-ci/docker-template.yml"

variables:
  IMAGE_PLATFORMS: 'linux/i386,linux/arm/v7'

download_dockerfile:
  stage: post_checkout
  image: busybox
  artifacts:
    paths:
    - image
  script:
  - test -z "${DOCKERFILE_URL}" || { mkdir -p image && wget -q -O image/Dockerfile "${DOCKERFILE_URL}"; }

read_application_tags:
  extends: .docker_support:.with_bare_image
  stage: post_build
  artifacts:
    paths:
    - tags
    - labels
  script:
  - set -euo pipefail
  - run() { docker run --rm "${IMAGE_NAME}:${BUILD_CACHE}" sh -c "${@}"; }

  - APP_VERSION="$(run '"${APP_HOME}/${APP_NAME}" -v' | sed -n -E 's/.* V ([^\t ]+).*/\1/p')"
  - APP_DATE="$(run 'stat -L -c %y "${APP_HOME}/${APP_NAME}"' | cut -d ' ' -f 1)"
  - BUILD_ID="$(date -u +%Y%m%d_%H%M%S)-${IMAGE_REVISION:-${CI_COMMIT_SHORT_SHA}}-$(od -An -N5 -tu4 </dev/urandom | tr -d ' ' | head -c8)"
  - RELEASE_DATE="$(run 'cat ${APP_HOME}/.release_date' | cut -d ' ' -f 1)"

  - mkdir -p tags
  - echo >tags/app_version "${IMAGE_NAME}:v${APP_VERSION}"
  - echo >tags/app_date "${IMAGE_NAME}:${APP_DATE}"
  - echo >tags/build_id "${IMAGE_NAME}:b${BUILD_ID}"
  - test "${APP_DATE}" = "${RELEASE_DATE}" || echo >tags/release_date "${IMAGE_NAME}:r${RELEASE_DATE}"

  - oci='org.opencontainers.image'
  - mkdir -p labels
  - echo >"labels/${oci}.version"  "${oci}.version=${APP_VERSION}"
