include:
  remote: "https://github.com/git-developer/docker-support/raw/v3.3.1/gitlab-ci/docker-support.yml"

stages:
- post_checkout

trigger_on_update:
  extends: .docker_support:.trigger_on_update
  stage: post_checkout
  dependencies: []

run_matrix_build:
  extends: .docker_support:.build_job
  stage: post_checkout
  trigger:
    include: .build.yml
    # required due to https://gitlab.com/gitlab-org/gitlab/-/issues/219342
    - remote: 'https://github.com/git-developer/solarview-base/raw/feature/buster/.gitlab-ci.yml'
    forward:
      pipeline_variables: true
  parallel:
    matrix:
      - RUNTIME_BASE_IMAGE: "debian:bullseye-slim"
        BUILD_ARGS:         "RUNTIME_BASE_IMAGE"
        BUILD_CONTEXT:      "image"
        IMAGE_PLATFORMS:    "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"
      - RUNTIME_BASE_IMAGE: "debian:buster-slim"
        BUILD_ARGS:         "RUNTIME_BASE_IMAGE"
        BUILD_CONTEXT:      "image"
        IMAGE_PLATFORMS:    "linux/amd64,linux/arm64,linux/arm/v7"
      - RUNTIME_BASE_IMAGE: "debian:buster-20220801-slim"
        BUILD_ARGS:         "RUNTIME_BASE_IMAGE"
        BUILD_CONTEXT:      "image"
        IMAGE_PLATFORMS:    "linux/arm/v6"
